# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoactivity',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='geoactivity',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sleepactivity',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sleepactivity',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stepactivity',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stepactivity',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
